services:
  postgres:
    env_file:
      - .env
    image: postgres
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - network

  client:
    env_file:
      - .env
    build: client
    ports:
      - "3000:3000"
    environment:
      - VITE_SERVER_BASE_URL=${VITE_SERVER_BASE_URL}
      - VITE_SSL=${VITE_SSL}

  server:
    env_file:
      - .env
    depends_on:
      - postgres
    build: server
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    networks:
      - network

networks:
  network:
    driver: bridge